### ISSUE TITLE
coveralls-python maintenance status

### ISSUE THREAD

**Issue by sodul** [TheKevJames/coveralls-python#393]
There seems to be little activity on the project in recent years with issues that are not being directly addressed such as #373. If the project is no longer being actively maintained should it be updated to reflect that?

**Comment by TheKevJames** [comment]
Hey all, maintainer here. This project ended up going unmaintained for a few years, mostly because between try to balance the competing priorities of supporting the latest `coverage` versions, python versions, etc as well as requests like #242 to maintain support for old versions of everything indefinitely, I found myself too fatigued to do anything.

In an effort to avoid getting hit by that issue again, I am coming down hard in favour of not supporting any end-of-life'd pythons, not supporting >5 year old (exact cutoff tbd) coverage versions, etc. Over the coming weeks, I'll aim to get everything cleaned up accordingly.

**Comment by sodul** [comment]
I'm very much in favor of only supporting versions of python that are still actively supported upstream. Folks that are sticking to older versions of python are taking security risks due to the lack of security fixes and should upgrade when possible.

Python 3.8 has much improved type annotation support which, combined with mypy, significantly improves bug detection.

I recommend that you look at pyupgrade as it is a great tool to help update existing code to newer python syntax with little work. We use pyugrade through gray, to auto format our codebase.

**Comment by TheKevJames** [comment]
@sodul thanks for the recommendation! I am indeed a fan of pyupgrade and have [bumped it up to `--py38-plus` just today](https://github.com/TheKevJames/coveralls-python/blob/962e22426b0fae0c63af6f149f8758b57958b5b6/.pre-commit-config.yaml#L91). You may also be interested in other linters in that file, lots of "autofix things for more modern python" stuff. Planning on making type hints required at some point, as well -- for now, I've used them wherever I touched code today, so it's probably close to the point where it's worth toggling 'em on in linting.

**Comment by tomato42** [comment]
> Folks that are sticking to older versions of python are taking security risks due to the lack of security fixes and should upgrade when possible.

with all due respect, this is FUD
